pinecone:
  type: pincone
  host: 'https://quickstart2-oqohknh.svc.aped-4627-b74a.pinecone.io'
  port: 8000
  index_name: canada-policy-index
  environment: 'us-east-1'
  dimension: 1024
  metric: 'cosine'
  cloud: 'aws'
  region: 'us-east-1'
model:
  model_type: Groq
  model_name: "llama-3.1-8b-instant"
  temperature: 0.7  # Control the randomness of model outputs
  max_tokens: 150 
embeddings:
  model_name: "thenlper/gte-large"